In [1]:
# 使用sklearn中的高斯贝叶斯
# 导包
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# 导入数据集
from sklearn import datasets
iris=datasets.load_iris()

In [6]:
print(type(iris))

AttributeError: index

In [7]:
print(iris.data)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
#切分数据集
Xtrain, Xtest, ytrain, ytest = train_test_split(iris.data, iris.target, random_state=42)

In [9]:
print(len(Xtrain), len(Xtest))

112 38


In [10]:
#建模
clf = GaussianNB()
clf.fit(Xtrain, ytrain)
pred = clf.predict(Xtest)
#测试准确率
accuracy_score(ytest, clf.predict(Xtest))

1.0

In [11]:
# 手写朴素贝叶斯分类器
# 导包
import numpy as np
import pandas as pd
import random

In [13]:
dataSet = pd.read_csv('../data//4_nb//iris.txt',header = None)

RangeIndex(start=0, stop=150, step=1)


In [16]:
display(dataSet[:5])

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [36]:
def randSplit(dataSet, rate):
    l = list(dataSet.index) #提取出索引
    random.shuffle(l) #随机打乱索引
    dataSet.index = l #将打乱后的索引重新赋值给原数据集
    n = dataSet.shape[0] #总行数
    m = int(n * rate) #训练集的数量
    train = dataSet.loc[range(m), :] #提取前m个记录作为训练集
    test = dataSet.loc[range(m, n), :] #剩下的作为测试集
    dataSet.index = range(dataSet.shape[0]) #更新原数据集的索引
    test.index = range(test.shape[0]) #更新测试集的索引
    return train, test

In [91]:
train, test = randSplit(dataSet, 0.8)
display(train[:5])
display(test[:5])

0    1    2    3                4
0  5.5  2.4  3.8  1.1  Iris-versicolor
1  4.7  3.2  1.3  0.2      Iris-setosa
2  6.7  3.0  5.2  2.3   Iris-virginica
3  5.6  2.5  3.9  1.1  Iris-versicolor
4  6.7  3.1  5.6  2.4   Iris-virginica

0    1    2    3                4
0  5.8  2.8  5.1  2.4   Iris-virginica
1  5.1  3.7  1.5  0.4      Iris-setosa
2  5.4  3.0  4.5  1.5  Iris-versicolor
3  5.0  3.4  1.5  0.2      Iris-setosa
4  6.5  3.0  5.2  2.0   Iris-virginica

In [109]:
def gnb_classify(train,test):
    labels = train.iloc[:,-1].value_counts().index #提取训练集的标签种类
    mean =[] #存放每个类别的均值
    std =[] #存放每个类别的方差
    pred = [] #存放测试集的预测结果
    for i in labels:
        item = train.loc[train.iloc[:,-1]==i,:] #分别提取出每一种类别
        m = item.iloc[:,:-1].mean() #当前类别的平均值
        # s = np.sum((item.iloc[:,:-1]-m)**2)/(item.shape[0]) #
        s = item.iloc[:, :-1].std() ** 2
        mean.append(m) #将当前类别的平均值追加至列表
        std.append(s) #将当前类别的方差追加至列表
    means = pd.DataFrame(mean,index=labels) #变成DF格式，索引为类标签
    stds = pd.DataFrame(std,index=labels) #变成DF格式，索引为类标签
    for j in range(test.shape[0]):
        iset = test.iloc[j,:-1].tolist() #当前测试实例
        iprob = np.exp(-1*(iset-means)**2/(stds*2))/(np.sqrt(2*np.pi*stds)) #正态分布公式
        # display(iset)
        # display(iprob)
        prob = 1 #初始化当前实例总概率
        for k in range(test.shape[1]-1): #遍历每个特征
            prob *= iprob[k] #特征概率之积即为当前实例概率
            # display(prob)
            # display(np.argmax(prob.values))
            cla = prob.index[np.argmax(prob.values)] #返回最大概率的类别
        pred.append(cla)
    # test['predict']=result
    acc = (test.iloc[:,-1]==pred).mean() #计算预测准确率
    print(f'模型预测准确率为{acc}')
    return test

In [112]:
for i in range(20):
    train,test= randSplit(dataSet, 0.8)
    gnb_classify(train,test)

模型预测准确率为0.9333333333333333
模型预测准确率为1.0
模型预测准确率为0.9666666666666667
模型预测准确率为0.9333333333333333
模型预测准确率为0.9666666666666667
模型预测准确率为0.9333333333333333
模型预测准确率为0.9333333333333333
模型预测准确率为1.0
模型预测准确率为0.9333333333333333
模型预测准确率为0.8666666666666667
模型预测准确率为0.8666666666666667
模型预测准确率为0.9
模型预测准确率为0.9666666666666667
模型预测准确率为0.9666666666666667
模型预测准确率为0.9666666666666667
模型预测准确率为0.9333333333333333
模型预测准确率为0.9
模型预测准确率为0.9666666666666667
模型预测准确率为0.9
模型预测准确率为0.8666666666666667


In [ ]:
# 使用朴素贝叶斯进行文档分类

In [113]:
def loadDataSet():
    dataSet=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
             ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
             ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
             ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
             ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
             ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']] #切分好的词条
    classVec = [0,1,0,1,0,1] #类别标签向量，1代表侮辱性词汇，0代表非侮辱性词汇
    return dataSet,classVec

In [115]:
dataSet,classVec = loadDataSet()

In [116]:
display(dataSet)
display(classVec)

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

[0, 1, 0, 1, 0, 1]

In [117]:
def createVocabList(dataSet):
    vocabSet = set() #创建一个空的集合
    for doc in dataSet: #遍历dataSet中的每一条言论
        vocabSet = vocabSet | set(doc) #取并集
        vocabList = list(vocabSet)
    return vocabList

In [118]:
vocabList = createVocabList(dataSet)
print(vocabList)

['stupid', 'love', 'stop', 'buying', 'has', 'I', 'please', 'my', 'cute', 'quit', 'mr', 'dog', 'licks', 'worthless', 'maybe', 'so', 'posting', 'how', 'him', 'steak', 'take', 'food', 'ate', 'problems', 'is', 'help', 'flea', 'park', 'dalmation', 'to', 'not', 'garbage']


In [119]:
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0] * len(vocabList) #创建一个其中所含元素都为0的向量
    for word in inputSet: #遍历每个词条
        if word in vocabList: #如果词条存在于词汇表中，则变为1
            returnVec[vocabList.index(word)] = 1
        else:
            print(f" {word} is not in my Vocabulary!" )
    return returnVec #返回文档向量

In [120]:
def get_trainMat(dataSet):
    trainMat = [] #初始化向量列表
    vocabList = createVocabList(dataSet) #生成词汇表
    for inputSet in dataSet: #遍历样本词条中的每一条样本
        returnVec=setOfWords2Vec(vocabList, inputSet) #将当前词条向量化
        trainMat.append(returnVec) #追加到向量列表中
    return trainMat

In [124]:
trainMat = get_trainMat(dataSet)
n = len(trainMat) #计算训练的文档数目
m = len(trainMat[0]) #计算每篇文档的词条数
# print(trainMat[3])
# print(sum(trainMat[3]))
print(n)
print(trainMat[0])

6
[0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0]


In [125]:
# Kaggle 旧金山犯罪预测
# 导包
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss

In [126]:
train = pd.read_csv('../data//4_nb//Kaggle/train.csv',parse_dates = ['Dates'])
test = pd.read_csv('../data//4_nb//Kaggle/test.csv',parse_dates = ['Dates'],index_col=0)

In [127]:
train.head()

Dates        Category                      Descript  \
0 2015-05-13 23:53:00        WARRANTS                WARRANT ARREST   
1 2015-05-13 23:53:00  OTHER OFFENSES      TRAFFIC VIOLATION ARREST   
2 2015-05-13 23:33:00  OTHER OFFENSES      TRAFFIC VIOLATION ARREST   
3 2015-05-13 23:30:00   LARCENY/THEFT  GRAND THEFT FROM LOCKED AUTO   
4 2015-05-13 23:30:00   LARCENY/THEFT  GRAND THEFT FROM LOCKED AUTO   

   DayOfWeek PdDistrict      Resolution                    Address  \
0  Wednesday   NORTHERN  ARREST, BOOKED         OAK ST / LAGUNA ST   
1  Wednesday   NORTHERN  ARREST, BOOKED         OAK ST / LAGUNA ST   
2  Wednesday   NORTHERN  ARREST, BOOKED  VANNESS AV / GREENWICH ST   
3  Wednesday   NORTHERN            NONE   1500 Block of LOMBARD ST   
4  Wednesday       PARK            NONE  100 Block of BRODERICK ST   

            X          Y  
0 -122.425892  37.774599  
1 -122.425892  37.774599  
2 -122.424363  37.800414  
3 -122.426995  37.800873  
4 -122.438738  37.771541

In [128]:
test.head()

Dates DayOfWeek PdDistrict                   Address  \
Id                                                                      
0  2015-05-10 23:59:00    Sunday    BAYVIEW   2000 Block of THOMAS AV   
1  2015-05-10 23:51:00    Sunday    BAYVIEW        3RD ST / REVERE AV   
2  2015-05-10 23:50:00    Sunday   NORTHERN    2000 Block of GOUGH ST   
3  2015-05-10 23:45:00    Sunday  INGLESIDE  4700 Block of MISSION ST   
4  2015-05-10 23:45:00    Sunday  INGLESIDE  4700 Block of MISSION ST   

             X          Y  
Id                         
0  -122.399588  37.735051  
1  -122.391523  37.732432  
2  -122.426002  37.792212  
3  -122.437394  37.721412  
4  -122.437394  37.721412

In [129]:
#对犯罪类别:Category; 用LabelEncoder进行编号
leCrime = LabelEncoder()
crime = leCrime.fit_transform(train.Category) #39种犯罪类型

In [141]:
days = pd.get_dummies(train.DayOfWeek)
district = pd.get_dummies(train.PdDistrict)

In [133]:
hour = train.Dates.dt.hour
hour = pd.get_dummies(hour)

(878049,)

In [139]:
# address = pd.get_dummies(train.Address)
len(train.loc[:, 'Address'].value_counts())

23228

In [136]:
print(train.shape, test.shape)

(878049, 9) (884262, 6)


In [142]:
#组合特征形成训练集
trainData = pd.concat([hour, days, district], axis = 1) #将特征进行左右拼接
trainData['crime'] = crime #追加标签列
trainData.head()

Dates  Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday  \
0     23       0       0         0       0         0        0          1   
1     23       0       0         0       0         0        0          1   
2     23       0       0         0       0         0        0          1   
3     23       0       0         0       0         0        0          1   
4     23       0       0         0       0         0        0          1   

   BAYVIEW  CENTRAL  INGLESIDE  MISSION  NORTHERN  PARK  RICHMOND  SOUTHERN  \
0        0        0          0        0         1     0         0         0   
1        0        0          0        0         1     0         0         0   
2        0        0          0        0         1     0         0         0   
3        0        0          0        0         1     0         0         0   
4        0        0          0        0         0     1         0         0   

   TARAVAL  TENDERLOIN  crime  
0        0           0     37  
1        0           0     21  
2        0           0     21  
3        0           0     16  
4        0           0     16

In [143]:
#得到测试集
days = pd.get_dummies(test.DayOfWeek)
district = pd.get_dummies(test.PdDistrict)
hour = test.Dates.dt.hour
hour = pd.get_dummies(hour)
testData = pd.concat([hour, days, district], axis=1)
testData.head()

0  1  2  3  4  5  6  7  8  9  ...  BAYVIEW  CENTRAL  INGLESIDE  MISSION  \
Id                                ...                                         
0   0  0  0  0  0  0  0  0  0  0  ...        1        0          0        0   
1   0  0  0  0  0  0  0  0  0  0  ...        1        0          0        0   
2   0  0  0  0  0  0  0  0  0  0  ...        0        0          0        0   
3   0  0  0  0  0  0  0  0  0  0  ...        0        0          1        0   
4   0  0  0  0  0  0  0  0  0  0  ...        0        0          1        0   

    NORTHERN  PARK  RICHMOND  SOUTHERN  TARAVAL  TENDERLOIN  
Id                                                           
0          0     0         0         0        0           0  
1          0     0         0         0        0           0  
2          1     0         0         0        0           0  
3          0     0         0         0        0           0  
4          0     0         0         0        0           0  

[5 rows x 41 columns]

In [144]:
#切分数据集
X_train, X_test, y_train, y_test = train_test_split(trainData.iloc[:,:-1],
                                                    trainData.iloc[:,-1],
                                                    test_size=0.2)

In [145]:
#训练模型
BNB = BernoulliNB()
BNB.fit(X_train, y_train)

#计算损失函数
propa = BNB.predict_proba(X_test)
logLoss=log_loss(y_test, propa)
print(logLoss)

2.6100908873558524


In [150]:
from sklearn.naive_bayes import MultinomialNB
#多项式分布朴素贝叶斯
mnb = MultinomialNB() #获取模型
mnb.fit(X_train,y_train) #训练模型
#计算损失函数
propa_mnb = mnb.predict_proba(X_test)
logLoss_mnb = log_loss(y_test, propa_mnb)
print(logLoss_mnb)

2.606643454595278


In [151]:
print(propa)
print(propa_mnb)

[[0.00121228 0.08642866 0.0004683  ... 0.04999086 0.0266955  0.00556435]
 [0.00537714 0.12338333 0.00021427 ... 0.08795306 0.04129813 0.02089897]
 [0.00128586 0.09454069 0.00027493 ... 0.05069216 0.02857351 0.00541528]
 ...
 [0.00148915 0.0718627  0.00060966 ... 0.05708828 0.04723701 0.00695939]
 [0.00148915 0.0718627  0.00060966 ... 0.05708828 0.04723701 0.00695939]
 [0.00241171 0.06528889 0.00057282 ... 0.0996303  0.01954773 0.00731881]]
[[0.00121268 0.08633204 0.00047122 ... 0.05132755 0.02855861 0.00590305]
 [0.00347467 0.11367749 0.00017568 ... 0.09482439 0.04262954 0.01940047]
 [0.00138328 0.09520998 0.00032233 ... 0.05015216 0.03041484 0.0057491 ]
 ...
 [0.00209125 0.07990231 0.00099565 ... 0.04853272 0.04802356 0.0071193 ]
 [0.00203775 0.07943936 0.00095858 ... 0.04916298 0.04799486 0.00713349]
 [0.00260664 0.06858678 0.00069954 ... 0.09079156 0.02066119 0.00742769]]


16
